### ISSUE TITLE
Error when entering oauth into DCS interface

### ISSUE THREAD

**Issue by ozdeadmeat** [jeffboulanger/twitch2dcs#7]
![Twitch2DCS_Broken](https://user-images.githubusercontent.com/11052863/59517532-26341000-8f07-11e9-8c24-f5ac7db05873.png)

Twitch2DCS is breaking mods.

Other mods working 100% when not using Twitch2DCS

Tacview
SRS Radio
LotATC

Error above is seen when attempting to do anything to the interface within DCS World. All other mods work ok without Twitch2DCS installed.

**Comment by rthom91** [comment]
It will throw an error right when you input the OAUTH code. You just have to restart the sim and it should work normally. You are however on an older version, grab the latest release.
https://github.com/jeffboulanger/twitch2dcs/releases/download/v1.1.0-beta/Twitch2DCS-1.1.0Beta.zip
